import json
import os

base = "C:/Users/user/Documents/trust-agent-desktop/src/data/roles"

def expand_file(lang, extra_content):
    fn = os.path.join(base, f"{lang}-language-tutor.json")
    with open(fn, "r", encoding="utf-8") as f:
        d = json.load(f)
    old_len = len(d["systemPrompt"])
    d["systemPrompt"] = d["systemPrompt"] + extra_content
    with open(fn, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    new_len = len(d["systemPrompt"])
    print(f"{lang}: {old_len} -> {new_len} chars {'OK' if new_len >= 10000 else 'STILL NEEDS MORE'}")

# Top up all under 10000 with language-specific additional content

expand_file("ukrainian", "\n\nHISTORICAL EVOLUTION:\nOld East Slavic (Kyivan Rus period) -> Middle Ukrainian (14th-18th century, Cossack era) -> Modern Ukrainian (19th century revival). Ukrainian was repeatedly suppressed: Ems Decree (1876) banned Ukrainian publications in the Russian Empire. Soviet Russification policies. Post-independence (1991) revival and standardization. The 2019 language law established Ukrainian as sole state language. Understanding this history is essential for appreciating the cultural significance of the language.\n\nPRONUNCIATION DRILLS:\nThe voiced glottal fricative g: practice saying h but with vocal cords vibrating. It is NOT a hard g. Compare: Ukrainian hovoriti (to speak) vs Russian govorit. The soft consonant pairs: practice with minimal pairs like lis (forest) vs lis-soft (fox). Ukrainian yi sound: unique to Ukrainian Cyrillic, combines the y glide with i.\n\nIDIOMATIC EXPRESSIONS:\nUkrainian proverbs: Bez truda nema plodu (Without labor there is no fruit). Holovnoye - zdorovya (The main thing is health). Kozhen kuznya svoho shchastya (Everyone is the blacksmith of their own happiness). These reflect core cultural values and build natural expression.")

expand_file("persian", "\n\nHISTORICAL EVOLUTION:\nOld Persian (Achaemenid Empire, 6th-4th century BCE, written in cuneiform) -> Middle Persian/Pahlavi (Sassanid Empire, 3rd-7th century CE) -> New Persian/Farsi (9th century CE onwards, after Islamic conquest). Persian is one of the oldest continuously used literary languages. The Shahnameh by Ferdowsi (10th century) deliberately used native Persian vocabulary to resist Arabic lexical dominance. Modern Persian preserves remarkable continuity with classical forms.\n\nPRONUNCIATION DRILLS:\nThe Persian q (uvular stop): produced much further back than k, at the uvula. Practice: qalam (pen), qaza (fate). The Persian x (voiceless velar fricative): like Scottish loch. The gh (voiced velar fricative): the voiced counterpart of x. Minimal pairs: kar (work) vs ghar (cave), sal (year) vs thal does not exist. The Persian r is a tap, not English r or French r.\n\nIDIOMATIC EXPRESSIONS:\nPersian is famous for its poetic expressions in daily speech: Daste shoma dard nakone (May your hand not hurt - thank you for effort), Ghorban-e shoma (I sacrifice myself for you - very formal you are welcome), Cheshm (Eye - meaning certainly/at your service), Taarof phrases: Befarmaeed (Please go ahead/help yourself), Ghabel nadare (It is not worthy of you - when giving a gift).\n\nTAAROF - THE PERSIAN POLITENESS SYSTEM:\nTaarof is an elaborate system of ritual politeness unique to Persian culture. It involves: offering something multiple times before acceptance, insisting on paying for others, self-deprecation while elevating others, using elaborate phrases where simple ones would suffice. Understanding taarof is essential for natural Persian communication and avoiding social errors.")

expand_file("hindi", "\n\nHISTORICAL EVOLUTION:\nOld Hindi/Early Hindi (Apabhramsha, 7th-14th century) -> Medieval Hindi (Bhakti period, Kabir, Tulsi, Mira) -> Modern Standard Hindi (19th century standardization based on Khari Boli dialect of Delhi). The Devanagari script derives from Brahmi (3rd century BCE) through Nagari. Hindi was established as an official language of India in 1949.\n\nPRONUNCIATION DRILLS - MINIMAL PAIRS:\nAspirated vs unaspirated: pal/phal (moment/fruit), kal/khal (time/skin), dal/dhal (lentil/shield), ban/bhan (forest/strain). Dental vs retroflex: tal/ttal (rhythm/postpone), das/ddas (ten/bite). Nasalized: haa/haaN (yes/are), mai/maiN (May/I). Practice these pairs until the distinctions are automatic.\n\nKINSHIP VOCABULARY:\nHindi has over 30 specific kinship terms with no English equivalents: chacha (father younger brother), tau (father elder brother), mama (mother brother), mausi (mother sister), bua (father sister), fufa (father sister husband), mami (mother brother wife), chachi (father younger brother wife). Learning these is essential for social interaction.\n\nIDIOMATIC EXPRESSIONS:\nHindi muhavare (idioms): Aankh ka tara (apple of the eye - beloved), Naak katna (nose cutting - to be shamed), Haath pair phailana (spread hands and feet - to beg), Naach na jaane aangan tedha (does not know dancing blames the courtyard - making excuses).")

expand_file("czech", "\n\nPRONUNCIATION DRILLS:\nR-hacek practice sequence: start with alternating r and zh rapidly (r-zh-r-zh), then blend them together. Practice in words: tri (three), reka (river), more (sea), dvorak, pritel (friend). The Czech tongue twister: Strc prst skrz krk (Stick a finger through the throat) - entirely consonants, demonstrating Czech tolerance for consonant-only syllables (r and l can be syllabic).\n\nSYLLABIC CONSONANTS:\nCzech allows r and l to be syllable nuclei (like vowels): vlk (wolf), krk (throat/neck), prst (finger), smrt (death), brno (the city). This creates words with no vowels at all that are perfectly natural in Czech.\n\nIDIOMATIC EXPRESSIONS:\nCzech has colorful idioms: Houby s octem (Mushrooms with vinegar - no way!), Trafil se jako slepy k housatum (Found it like a blind man finds goslings - got lucky), Leze mi to na nervy (It crawls on my nerves - it annoys me), Je mu to buran (Hes a boor - he is uncouth). Czech humor and irony permeate the language.\n\nDIMINUTIVES:\nCzech uses diminutives extensively to express affection, smallness, or familiarity. Multiple levels of diminution: pes (dog) -> pesek -> pesecek. pivo (beer) -> pivko -> pivecko. This system is productive and culturally important.")

expand_file("vietnamese", "\n\nHISTORICAL EVOLUTION:\nVietnamese was historically written in Chinese characters (chu Han) and a Vietnamese adaptation called chu Nom. The current Latin-based script (chu quoc ngu) was developed by Portuguese and French missionaries in the 17th century and adopted nationally in the early 20th century. Vietnamese vocabulary has significant Chinese-origin layers (approximately 60% of vocabulary), but the grammar is completely different from Chinese.\n\nMINIMAL TONE PAIRS:\nThe classic ma set: ma (ghost, level), ma (cheek, rising), ma (but, falling), ma (tomb, dipping), ma (horse, creaky), ma (rice seedling, broken). Practice also with ba: ba (three, level), ba (random, rising), ba (already, falling/context). Tone perception training is as important as production - spend equal time listening and producing.\n\nCLASSIFIER SYSTEM:\nVietnamese uses classifiers (loai tu) with nouns: cai (general objects), con (animals, some objects), quyen (books), buc (pictures, letters), chiec (vehicles, individual items from a pair). Example: mot con cho (one CL dog), hai cai ban (two CL tables). Similar to Chinese and Japanese classifier systems.")

expand_file("punjabi", "\n\nHISTORICAL EVOLUTION:\nPunjabi descends from Shauraseni Prakrit through the Apabhramsha stage. Literary Punjabi tradition begins with Baba Farid (12th century Sufi poet). The Sikh scripture Guru Granth Sahib (compiled 1604) is written in multiple languages including Punjabi in Gurmukhi script. Bulleh Shah, Waris Shah (Heer Ranjha), and Sultan Bahu are major classical poets.\n\nPRONUNCIATION DRILLS - TONAL MINIMAL SETS:\nTone practice: ghorha (horse, low tone from historical voiced aspirate gh) vs gorha (unripe, level) vs korha (bitter, high from historical voiceless aspirate kh). Practice the three tones in pairs before attempting them in sentences. The musical quality of Punjabi makes it distinctive among Indo-Aryan languages.\n\nIDIOMATIC EXPRESSIONS:\nPunjabi muhavare: Pehlan pehlan hon khushi (First first happens happiness - initial honeymoon phase), Mitti pao (Put dirt on it - forget it), Jatta di saag (Jat farmer's mustard greens - simple but hearty), Hatt ja pareshaan (Go away troublesome one - playful dismissal). Punjabi humor and earthiness permeate the language.\n\nGURBANI READING:\nFor learners interested in Sikh scripture, Gurbani reading requires understanding archaic Punjabi vocabulary, Braj Bhasha influence, and the special conventions of scriptural Gurmukhi. This is a specialized track within Punjabi learning.")

expand_file("spanish", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nSpanish has 5 pure vowels (a, e, i, o, u) with consistent pronunciation regardless of position. Consonants: the distinction between b/v (which are the SAME sound in Spanish - a bilabial that varies between stop /b/ after pause/nasal and fricative in other positions), the Spanish r (single tap) vs rr (multiple trill), the jota /x/ (voiceless velar fricative in most dialects, uvular in some), the enye /ny/ (palatal nasal), and the ll (varies from palatal lateral to /y/ to /zh/ to /sh/ depending on dialect).\n\nSUBJUNCTIVE MOOD - THE SPANISH CHALLENGE:\nThe subjunctive is the most difficult aspect for English speakers. Present subjunctive: irregular stems (haya, sea, vaya, sepa, de, este). Imperfect subjunctive: two forms (-ra and -se, both acceptable). Triggers: WEIRDO (Wishes, Emotions, Impersonal expressions, Recommendations, Doubt/Denial, Ojala). Si clauses: si + imperfect subjunctive + conditional. Advanced: pluperfect subjunctive for contrary-to-fact past conditions.\n\nDIALECTAL VARIATION:\nCastilian Spanish: distinction between s and th (distincion). Andalusian: seseo (s for both), aspiration of s, loss of final consonants. Latin American: general seseo, voseo in Argentina/Uruguay/Central America (vos instead of tu with own verb forms). Mexican: clear consonants, moderate pace. Caribbean: weakened consonants, rapid pace. Rioplatense (Argentina): sheismo (ll/y pronounced as sh or zh), Italian intonation influence.\n\nEXAM PREPARATION:\nDELE (Diplomas de Espanol como Lengua Extranjera): A1-C2, administered by Instituto Cervantes. SIELE (digital, immediate results, valid 5 years). AP Spanish (US). GCSE/A-Level Spanish (UK boards). Each DELE level tests reading, writing, listening, and speaking.")

expand_file("romanian", "\n\nVERB SYSTEM:\nRomanian verbs are organized into 4 conjugation groups (like Latin, from which they descend): Group I (-a: a canta/to sing), Group II (-ea: a avea/to have), Group III (-e: a face/to do), Group IV (-i/-i: a dormi/to sleep, a hotari/to decide). Tenses: present, imperfect (descriptive past), perfect compus (conversational past, like French passe compose), perfect simplu (narrative past, mainly literary/Southern), pluperfect, future (voi + infinitive or o sa + subjunctive). The subjunctive (sa + conjugated verb) is used far more than in other Romance languages, replacing the infinitive in many contexts.\n\nIDIOMATIC EXPRESSIONS:\nRomanian expressions: A-i merge cuiva mintea la ceva (for ones mind to go to something - to crave), A da din casa (to give from the house - to waste/squander), A-si baga nasul (to stick ones nose in - to meddle), A pune paie pe foc (to put straw on fire - to make things worse). Romanian proverbs: Cine se scoala de dimineata departe ajunge (He who wakes early goes far).\n\nHISTORICAL EVOLUTION:\nVulgar Latin in the Roman province of Dacia -> Proto-Romanian (6th-10th century) -> Old Romanian (16th century, first texts) -> Modern Romanian. Romanian uniquely among Romance languages had no unbroken written tradition from Latin, making its survival remarkable. Slavic influence (10-15% vocabulary), Hungarian, Turkish, Greek, and French (19th century re-Romanization movement) all contributed layers to the vocabulary.")

expand_file("urdu", "\n\nHISTORICAL EVOLUTION:\nUrdu developed as a contact language (zabaan-e-urdu = language of the camp/army) in the Delhi Sultanate period (13th century) from the interaction of Khari Boli Hindi with Persian, Arabic, and Turkic. It became the court language of the Mughal Empire and was standardized as a literary language in the 18th-19th centuries. Urdu was adopted as the national language of Pakistan at independence (1947). The name Urdu itself comes from the Turkish word ordu (army/camp).\n\nPRONUNCIATION DRILLS:\nPharyngeal ain practice: constrict the throat muscles below the tongue root while voicing - the sound comes from deep in the throat. Compare: aam (common, with ain) vs aam (mango, with alif). Aspirated pairs: kal/khal (time/skin), dal/dhal (lentil/shield), pal/phal (moment/fruit). Retroflex pairs: dental ta vs retroflex tta, dental da vs retroflex dda.\n\nIDIOMATIC EXPRESSIONS:\nUrdu muhavare and zarb-ul-masal (proverbs): Thokar khana (to stumble - to learn from mistakes), Naak par gussa hona (anger on the nose - to be very angry), Andhere mein teer chalana (to shoot arrows in the dark - to guess), Jaise ko taisa (tit for tat).")

expand_file("greek", "\n\nHISTORICAL EVOLUTION:\nMycenaean Greek (Linear B, 1450 BCE) -> Archaic/Classical Greek (8th-4th century BCE, Homer, tragedy, philosophy) -> Koine Greek (Hellenistic period, language of New Testament) -> Byzantine/Medieval Greek (4th-15th century CE) -> Modern Greek (Demotic won over Katharevousa in 1976). The diglossia between Katharevousa (puristic, archaic) and Demotic (vernacular) was resolved in favor of Demotic as the official standard in 1976.\n\nPRONUNCIATION DRILLS:\nBeta as v: vaso, vivlio, varos. Delta as dh: dhiavasma, dhouleya. Gamma as voiced velar fricative before a/o/u: ghata, ghonya; as y before e/i: gheros, ghiaghia. Practice the difference between chi (as in Scottish loch) and kappa (as in English k).\n\nIDIOMATIC EXPRESSIONS:\nGreek idioms: Pio kala pente kai sto heri (Better five and in the hand - a bird in the hand), Apo to stoma sou kai sto Theou to afti (From your mouth to Gods ear - may it come true), Me ta kila den perpatane i agapi (Love does not walk with kilograms - love cannot be measured).")

expand_file("catalan", "\n\nHISTORICAL EVOLUTION:\nCatalan descends from Vulgar Latin spoken in the northeast of the Iberian Peninsula and southern France. Earliest texts date to the 12th century. It was the language of the Crown of Aragon, one of the most powerful Mediterranean states. Suppressed under Franco (1939-1975), with public use banned. Since 1978, it has been co-official with Spanish in Catalonia, Valencia, and the Balearic Islands, and the sole official language in Andorra.\n\nPRONUNCIATION DRILLS:\nThe neutral vowel (schwa): practice in unstressed positions: casa /kaze/ (house), pare /pare/ (father). The geminate l (punt volat): col-laborar, intel-ligent - hold the l sound longer. The ny palatal nasal: Catalunya, any, company. The tx affricate: cotxe (car), fletxa (arrow).\n\nIDIOMATIC EXPRESSIONS:\nCatalan expressions: Fer el bonic (to make the pretty one - to show off), Anar de bolic (to go on a spree), Ploure a bots i barrals (to rain in barrels - to pour), Qui no vulgui pols que no vagi a l-era (who does not want dust should not go to the threshing floor - if you cannot stand the heat stay out of the kitchen). Sant Jordi: the tradition of giving books and roses.\n\nEXAM PREPARATION:\nJunta Permanent de Catala certificates: Basico (A1-A2), Elemental (B1), Intermedi (B2), Suficiencia (C1), Superior (C2). Required for certain public sector jobs in Catalonia and the Balearic Islands. CIEFC certificates for international recognition.")

expand_file("german", "\n\nPRONUNCIATION DRILLS - MINIMAL PAIRS:\nUmlaut vowels: Mutter/Muetter (mother/mothers), Bruder/Brueder (brother/brothers), Boden/Boeden (floor/floors). The ich-laut vs ach-laut: ich /ich/ (palatal fricative after front vowels) vs ach /ax/ (velar fricative after back vowels): Kuchen (cake) vs kochen (cook), Milch (milk) vs Buch (book). Practice the r: standard German uses a uvular fricative or approximant, not the English r.\n\nIDIOMATIC EXPRESSIONS:\nGerman compound words (Komposita) create single words for complex concepts: Schadenfreude (pleasure at others misfortune), Weltanschauung (worldview), Zeitgeist (spirit of the age), Fernweh (longing for distant places - opposite of Heimweh/homesickness). German idioms: Da steppt der Baer (the bear dances there - its a great party), Ich verstehe nur Bahnhof (I only understand train station - I dont understand anything), Tomaten auf den Augen haben (to have tomatoes on your eyes - to be oblivious).")

expand_file("korean", "\n\nHISTORICAL EVOLUTION:\nOld Korean (Three Kingdoms period) -> Middle Korean (10th-16th century, preserved in Hunminjeongeum manuscript explaining Hangul creation) -> Modern Korean (17th century onwards). Before Hangul (1443), Korean was written using Chinese characters (Hanja) adapted through Idu and Hyangchal systems. Hangul was created specifically because Chinese characters were inadequate for representing Korean sounds. The UNESCO Memory of the World Programme recognizes the Hunminjeongeum as a masterpiece of linguistic design.\n\nIDIOMATIC EXPRESSIONS:\nKorean sajasongeo (four-character idioms from Chinese): ilseokijo (one stone two birds - killing two birds with one stone), gongjungsangak (castles in the air - unrealistic plans). Daily expressions: daebak (jackpot - amazing!), fighting/hwaiting (encouragement), aigoo (oh my - exclamation), jinjja (really), heol (OMG - shock).")

expand_file("turkish", "\n\nHISTORICAL EVOLUTION:\nOld Turkic (Orkhon inscriptions, 8th century CE) -> Ottoman Turkish (heavily influenced by Arabic and Persian, written in Arabic script) -> Modern Turkish (Ataturk language reforms 1928: adoption of Latin script, purification of vocabulary replacing Arabic/Persian words with Turkic equivalents). The 1928 script reform was one of the most dramatic language reforms in history, requiring the entire nation to learn a new alphabet within months.\n\nPRONUNCIATION DRILLS:\nUndotted i practice: compare it with i - they are completely different vowels. iyi (good) uses dotted i, isik (light) uses undotted i. Front rounded vowels: oe as in goez (eye), ue as in guenes (sun). Practice vowel harmony chains: evlerinden (from their houses, all front vowels), odalarinda (in their rooms, all back vowels).\n\nIDIOMATIC EXPRESSIONS:\nTurkish deyimler (idioms): Gozden dusmek (to fall from the eye - to fall out of favor), Agzinda bakla islanmamak (not to soak beans in the mouth - to be unable to keep a secret), El elden ustundur (Hand is above hand - there is always someone better), Damlaya damlaya gol olur (Drop by drop becomes a lake - persistence).")

expand_file("welsh", "\n\nHISTORICAL EVOLUTION:\nPrimitive Welsh (6th-8th century) -> Old Welsh (9th-12th century, earliest poetry: Aneirin, Taliesin) -> Middle Welsh (12th-14th century, the Mabinogion tales) -> Modern Welsh (15th century onwards, William Morgan Bible translation 1588 standardized the language). Welsh has the oldest continuous literary tradition in Britain. The language declined during industrialization but has been revitalized since the Welsh Language Act 1993 and the Welsh Language (Wales) Measure 2011.\n\nPRONUNCIATION DRILLS:\nLL (voiceless lateral fricative): place tongue as for l, then blow air past the sides without voicing. Practice: llan (parish), llaeth (milk), llaw (hand), llyfr (book). CH (voiceless velar fricative): like Scottish loch. Practice: chi (you), bach (small), chwech (six). DD (voiced dental fricative): like English th in this. Practice: dda (good), ddoe (yesterday).\n\nIDIOMATIC EXPRESSIONS:\nWelsh expressions: Dwr dan bont (water under bridge), Heb ei fai heb ei eni (without his fault without his birth - nobody is faultless), Gorau chwarae cyd-chwarae (the best game is playing together - teamwork). Welsh culture: Eisteddfod vocabulary, rugby terminology, Welsh cakes (pice ar y maen).\n\nEXAM PREPARATION:\nWJEC/CBAC Welsh language examinations at GCSE and A-Level. The Canolfan Cymraeg i Oedolion certificates for adult learners. Welsh language requirements for certain public sector positions.")

expand_file("norwegian", "\n\nHISTORICAL EVOLUTION:\nOld Norse (Viking Age, 8th-14th century, shared with Iceland, Denmark, Sweden) -> Middle Norwegian (14th-16th century) -> Danish rule period (1380-1814, Norwegian written language was Danish) -> Modern Norwegian: two standards emerged - Bokmal (evolved from Danish-influenced written Norwegian, promoted by Knud Knudsen) and Nynorsk (created by Ivar Aasen from rural Norwegian dialects in the 1850s).\n\nPRONUNCIATION DRILLS:\nPitch accent: practice pairs like bonden (accent 1, the farmer) vs bonden (accent 2, the tie/bond). Front rounded vowels: y as in ny (new), u as in hus (house), oe as in hoere (hear). The kj-sound (voiceless palatal fricative): kjole (dress), kjoere (drive) - distinct from sj-sound (voiceless postalveolar fricative): sjanse (chance), sjokolade (chocolate).\n\nIDIOMATIC EXPRESSIONS:\nNorwegian uttrykk: Det er ikke bare bare (It is not just just - it is not that simple), A vaere midt i smoeroeyet (to be in the middle of the butter eye - to be in the best position), Ull i munnen (wool in the mouth - to mumble), Det blaser en vind (a wind blows - trouble is coming).")

expand_file("swedish", "\n\nHISTORICAL EVOLUTION:\nOld Swedish (Old Norse period) -> Middle Swedish (14th-16th century) -> Modern Swedish (from 17th century, standardized through the Bible translation and the Swedish Academy). Swedish spelling was reformed in 1906 (removing silent letters and regularizing patterns). The Swedish Academy (founded 1786) maintains the official dictionary and word list.\n\nPRONUNCIATION DRILLS:\nSJ-sound: varies dramatically by dialect - practice the hushing variant common in standard Swedish. Practice: sjuk (sick), skjorta (shirt), station (same sj-sound despite different spelling). TJ/KJ-sound (voiceless palatal fricative): kjol (skirt), tjugo (twenty). Pitch accent pairs: anden (accent 1, the duck) vs anden (accent 2, the spirit), tomten (accent 1, the yard) vs tomten (accent 2, Santa/the gnome).\n\nIDIOMATIC EXPRESSIONS:\nSwedish uttryck: Att laga mat i lagom (to cook food in lagom - moderation). Det ar ingen ko pa isen (there is no cow on the ice - there is no rush/danger). Att kasta paerlor for svin (to throw pearls before swine). Swedish compound words: samhalle (society), fritid (free time), medborgarskap (citizenship).")

expand_file("danish", "\n\nPRONUNCIATION DRILLS:\nSoft d (blaest d): place tongue as for l but let air pass over the blade of the tongue. Practice: mad (food), roed (red), lade (to let). STOD practice: compare words with and without stod - this requires learning to make a brief glottal constriction during a vowel. The r: Danish r is a uvular approximant that colors adjacent vowels significantly.\n\nIDIOMATIC EXPRESSIONS:\nDanish expressions: At have en hoene at plukke med nogen (to have a hen to pluck with someone - to have a bone to pick), Det er hip som hap (it is hip as hap - six of one half a dozen of the other), At vaere oppe pa maelkeboetten (to be up on the buttercup - to be alert/on top of things).\n\nHISTORICAL EVOLUTION:\nOld Norse -> Old Danish (Viking Age) -> Middle Danish (13th-16th century) -> Modern Danish (from 16th century, Bible translation 1550). Danish pronunciation has undergone dramatic lenition (consonant weakening) over centuries, creating the famous gap between spelling and pronunciation. This historical sound change explains why written Danish looks similar to Norwegian/Swedish but sounds so different.")

expand_file("hungarian", "\n\nHISTORICAL EVOLUTION:\nProto-Uralic -> Proto-Ugric -> Proto-Hungarian -> Old Hungarian (896 CE arrival in Carpathian Basin, Rovash runic script) -> Middle Hungarian (16th-18th century) -> Modern Hungarian (19th century language reform/nyelvujitas which created thousands of new words). The 19th century language reform was remarkable: hundreds of writers and intellectuals systematically created modern vocabulary from Hungarian roots, replacing Latin and German loanwords.\n\nPRONUNCIATION DRILLS:\nFront rounded vowels: oe (like German schoen) and ue (like German Muenchen). Practice: koennyue (easy - contains both oe and ue!), tuez (fire), uel (sit), oet (five). Long vowels: compare tul (beyond) vs tuul (does not exist) - length changes meaning. The sz/s distinction: sz = s sound (as in sun), s = sh sound (as in ship) - OPPOSITE of English intuition!\n\nIDIOMATIC EXPRESSIONS:\nHungarian koezmondasok: Aki mer, az nyer (Who dares wins), Nem eszik olyan forron a kását (You do not eat the porridge as hot as it is served - things are not as bad as they seem), Aki koeroezt akar enni, ne sajnalja a koermeit (Who wants to eat walnuts should not mind their fingernails - no pain no gain).")

expand_file("dutch", "\n\nHISTORICAL EVOLUTION:\nOld Dutch (Frankish period) -> Middle Dutch (12th-15th century) -> Modern Dutch (from 16th century, standardized through the Statenvertaling Bible 1637). The Dutch language underwent a conscious standardization effort. Afrikaans, spoken in South Africa, is a daughter language of Dutch that diverged from the 17th century Cape Colony Dutch.\n\nPRONUNCIATION DRILLS:\nThe g/ch sound: practice the uvular/velar fricative. Compare Northern harsh g (Amsterdam) with Southern soft g (Belgium/Brabant). The ui diphthong: huis (house) - no English equivalent, starts from a centralized position. The ij/ei diphthong: trein (train), wijn (wine) - both sound like English 'ay' with a slightly different starting position.\n\nIDIOMATIC EXPRESSIONS:\nDutch uitdrukkingen: Dat is een appeltje-eitje (that is a little apple-egg - piece of cake), Nu komt de aap uit de mouw (now the monkey comes out of the sleeve - the truth comes out), Met de noorderzon vertrekken (to leave with the northern sun - to disappear without trace), Iets door de vingers zien (to see something through the fingers - to overlook).")

expand_file("cantonese", "\n\nHISTORICAL EVOLUTION:\nCantonese preserves many features of Middle Chinese (Tang Dynasty period, 7th-10th century) that Mandarin lost, including: final consonants -p, -t, -k, -m, the checked/entering tones, and more tonal distinctions. This makes Cantonese valuable for understanding classical Chinese poetry, which was composed with these features in mind. Cantonese has been the dominant Chinese variety in Hong Kong since the British colonial period and in overseas Chinese communities worldwide.\n\nPRONUNCIATION DRILLS:\nTone pairs: si1 (poem) vs si2 (history) vs si3 (try) vs si4 (time) vs si5 (market) vs si6 (yes). Practice final consonants: saap (ten, -p stop), baat (eight, -t stop), luk (six, -k stop) - all unreleased. Practice initial contrasts: gau (nine) vs kau (to hook) - unaspirated vs aspirated.\n\nIDIOMATIC EXPRESSIONS:\nCantonese expressions: Mo lei tau (nonsensical/absurd - associated with Stephen Chow comedy style), Sik dak gei do (know how much - asking about knowledge), Mou man tai (no problem), Gam yeung (like that), Dak (OK/can). Cantonese slang evolves rapidly in Hong Kong and is an important part of cultural literacy.")

expand_file("arabic", "\n\nHISTORICAL EVOLUTION:\nPre-Islamic Arabic poetry tradition -> Classical Arabic (language of the Quran, 7th century CE) -> Medieval Arabic (Islamic Golden Age scientific, philosophical, literary texts) -> Modern Standard Arabic (19th century Nahda/Renaissance movement). Arabic is the liturgical language of Islam (1.8 billion Muslims) and has contributed thousands of loanwords to European languages: algorithm, algebra, alcohol, coffee, cotton, magazine, admiral, zero.\n\nPRONUNCIATION DRILLS:\nPharyngeal ain: constrict the pharynx while voicing. Practice: ain (eye), arabi (Arabic), amal (work/hope). Emphatic consonants: compare sin/saad (s plain vs emphatic), dal/daad (d plain vs emphatic) - the emphatic consonant makes surrounding vowels sound darker/deeper. Uvular qaf: produced at the uvula, further back than k. Practice: qalam (pen), Quran, qahwa (coffee).\n\nIDIOMATIC EXPRESSIONS:\nArabic proverbs (amthal): Al-ilm nour (Knowledge is light), Man jadda wajada (He who strives finds), Al-sabr miftah al-faraj (Patience is the key to relief), Akhir al-tibb al-kayy (The last resort of medicine is cauterization - desperate times call for desperate measures).")

expand_file("mandarin", "\n\nHISTORICAL EVOLUTION:\nMandarin (Guanhua/Putonghua) was standardized in the early 20th century based on the Beijing dialect. The script reform: Simplified characters were promulgated by the PRC government in 1956-1964 to increase literacy. Taiwan, Hong Kong, and Macau continue using Traditional characters. Pinyin romanization (adopted 1958) is the standard system for teaching pronunciation.\n\nPRONUNCIATION DRILLS:\nRetroflex initials: zh /tʂ/, ch /tʂh/, sh /ʂ/, r /ɻ/ vs flat z /ts/, c /tsh/, s /s/. Practice: zhi (know) vs zi (character), chi (eat) vs ci (word), shi (yes) vs si (four). Tone pairs: ma1/ma2/ma3/ma4 practice. Tone sandhi: practice third-tone sequences: ni hao (you good = hello) - ni becomes second tone before hao.\n\nIDIOMATIC EXPRESSIONS:\nChengyu (four-character idioms from classical stories): yi shi er niao (one stone two birds), ban tu er fei (halfway and stop - to give up), ma ma hu hu (horse horse tiger tiger - so-so), ren shan ren hai (people mountain people sea - huge crowds). Chengyu mastery marks advanced fluency.")

expand_file("russian", "\n\nHISTORICAL EVOLUTION:\nOld East Slavic (Kyivan Rus, 9th-14th century) -> Old Russian (14th-17th century) -> Modern Russian (standardized from 18th century by Lomonosov and Pushkin). Peter the Great reformed the Cyrillic script in 1708. The 1917 spelling reform removed several letters. Pushkin (1799-1837) is considered the founder of modern literary Russian.\n\nPRONUNCIATION DRILLS:\nVowel reduction: Practice pronouncing Moskva (Moscow) as /maskva/ with the unstressed o becoming a. Moloko (milk) as /malako/. This akanye is the most distinctive feature of standard Russian pronunciation. Hard/soft pairs: compare mat (checkmate, hard t) vs mat-soft-sign (mother, soft t) - the palatalization changes meaning.\n\nIDIOMATIC EXPRESSIONS:\nRussian poslovitsy: Bez truda ne vytashchish i rybku iz pruda (Without effort you will not pull even a small fish from the pond - no pain no gain), Lyubish katatsa - lyubi i sanochki vozit (If you like to ride, love pulling the sleigh too - take the rough with the smooth), V tihom omute cherti vodyatsya (In a still pool devils dwell - still waters run deep).")

expand_file("polish", "\n\nHISTORICAL EVOLUTION:\nOld Polish (10th-15th century, first texts: Bogurodzica hymn) -> Middle Polish (16th-18th century, Golden Age of Polish literature, Mikolaj Rej, Jan Kochanowski) -> Modern Polish (19th century, partitioned Poland used language as a tool of national identity). The Krakow-Warsaw literary tradition standardized the language.\n\nPRONUNCIATION DRILLS:\nThree sibilant series: Practice si/zi/ci (palatal) vs sz/rz/cz (retroflex) vs s/z/c (alveolar). Minimal set: Szyja (neck, retroflex) vs sia (self-reflexive, palatal) vs sa (they are, alveolar). Nasal vowels: Compare be (without nasal) with be-ogonek (they will be, with nasal). Consonant clusters: start simple (st, sp, sk) and build (str, spr, wstr, prz, trz).\n\nIDIOMATIC EXPRESSIONS:\nPolish przyslowia: Nie moj cyrk nie moje malpy (Not my circus not my monkeys - not my problem), Co ma piernik do wiatraka (What does gingerbread have to do with a windmill - apples and oranges), Gdzie kucharek szesc tam nie ma co jesc (Where there are six cooks there is nothing to eat - too many cooks).")

expand_file("portuguese", "\n\nPRONUNCIATION DRILLS:\nNasal vowels: practice am/an, em/en, im/in, om/on, um/un in word-final and pre-consonantal positions. The lh palatal lateral: filho (son), trabalho (work), olho (eye). The nh palatal nasal: vinho (wine), minha (my-F), banho (bath). EP unstressed vowel reduction: practice saying verde as /verd/ (almost no final vowel), leite as /lait/ (heavily reduced).\n\nIDIOMATIC EXPRESSIONS:\nPortuguese expressions: Quem nao tem cao caca com gato (Who has no dog hunts with cat - make do with what you have), Agua mole em pedra dura tanto bate ate que fura (Soft water on hard stone beats until it pierces - persistence), De grao em grao a galinha enche o papo (Grain by grain the chicken fills its crop - little by little).")

expand_file("french", "\n\nPRONUNCIATION DRILLS - MINIMAL PAIRS:\nNasal vowels: beau/bon (no nasal vs nasal), sa/sang (oral vs nasal a), fait/fin (oral vs nasal e). The French u vs ou: tu/tout (you/all), vu/vous (seen/you), su/sous (known/under). The French r: practice gargling position - uvular fricative, NOT English r. Silent letters: practice reading aloud focusing on which consonants are silent.\n\nIDIOMATIC EXPRESSIONS:\nFrench expressions courantes: Avoir le cafard (to have the cockroach - to be depressed), Poser un lapin (to place a rabbit - to stand someone up), Raconter des salades (to tell salads - to tell lies), Couper les cheveux en quatre (to cut hairs in four - to split hairs), Il pleut des cordes (it rains ropes - it is pouring).")

print("\nAll top-ups complete!")
