import json
import os

base = "C:/Users/user/Documents/trust-agent-desktop/src/data/roles"

def expand_file(lang, extra_content):
    fn = os.path.join(base, f"{lang}-language-tutor.json")
    with open(fn, "r", encoding="utf-8") as f:
        d = json.load(f)
    old_len = len(d["systemPrompt"])
    d["systemPrompt"] = d["systemPrompt"] + extra_content
    with open(fn, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    new_len = len(d["systemPrompt"])
    print(f"{lang}: {old_len} -> {new_len} chars {'OK' if new_len >= 10000 else 'NEEDS MORE'}")
    return new_len

# Hungarian
expand_file("hungarian", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nHungarian has 14 vowel phonemes: 7 short (a, e, i, o, oe, u, ue) and 7 long counterparts (aa, ee, ii, oo, ooe, uu, uue). Length is PHONEMIC and changes meaning. Front rounded vowels oe/ooe and ue/uue have no English equivalents. Consonants include palatalized variants: ty, gy, ny (palatal stops/nasal), and the distinction between s (=sh) and sz (=s) and between cs (=ch) and c (=ts) - the spelling conventions are counterintuitive for English speakers.\n\nVOWEL HARMONY:\nHungarian vowels divide into back (a, aa, o, oo, u, uu), front unrounded (e, ee, i, ii), and front rounded (oe, ooe, ue, uue). Suffixes must harmonize with the stem vowel: back-vowel words take back-vowel suffixes (haz-ban = in house), front-vowel words take front-vowel suffixes (szek-ben = in chair). Some suffixes have three variants (back/front unrounded/front rounded). This harmony system affects EVERY suffix in the language.\n\nCASE SYSTEM:\nHungarian has 18 grammatical cases (some analyses count more). Beyond the familiar nominative, accusative, dative, instrumental, these include: inessive (-ban/-ben, in), elative (-bol/-bol, out of), illative (-ba/-be, into), superessive (-n/-on/-en/-oen, on), delative (-rol/-rol, off of), sublative (-ra/-re, onto), adessive (-nal/-nel, at/near), ablative (-tol/-tol, from near), allative (-hoz/-hez/-hoez, to/toward), translative (-va/-ve, becoming), terminative (-ig, until), causal-final (-ert, for/because), essive-formal (-kent, as/like), distributive (-nkent, per each), and more.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Not understanding vowel harmony - EVERY suffix must harmonize.\n2. Overwhelmed by the case system - but it is highly regular.\n3. Verb conjugation: definite vs indefinite conjugation based on whether the object is definite.\n4. Word order: topic-focus-verb in neutral, but highly flexible for emphasis.\n5. Not producing front rounded vowels oe and ue.\n6. Confusing the spelling conventions: s=sh, sz=s, cs=ch, c=ts, gy=dy, ny=ny, ty=ty.\n\nDEFINITE VS INDEFINITE CONJUGATION:\nHungarian verbs have TWO complete conjugation paradigms: indefinite (used when object is indefinite or absent) and definite (used when object is definite). Latok egy hazat (I see a house, indefinite) vs Latom a hazat (I see the house, definite). This distinction affects every verb in every tense.\n\nCULTURAL CONTEXT:\nHungarian (Magyar) is a Finno-Ugric language, NOT Indo-European - unrelated to neighboring Slavic, Germanic, or Romance languages. Closest relatives are Khanty and Mansi (in Siberia) and distantly Finnish/Estonian. Hungarian culture: thermal bath vocabulary, goulash and paprika cuisine, Tokaji wine, csardas dance, Budapest as cultural center.")

# Polish
expand_file("polish", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nPolish consonants include extensive sibilant series: s /s/, z /z/, sz /sh/, rz/zh /zh/, cz /ch/, dz /dz/, c /ts/, dz-hacek /dzh/, plus PALATALIZED sibilants unique to Polish: si /si/, zi /zi/, ci /tsi/, dzi /dzi/ (written with i before vowels or with acute accent before consonants). The distinction between sz/rz/cz (retroflex) and si/zi/ci (palatal) is critical and has no English parallel. Polish also has the nasal vowels: a-ogonek /on/ and e-ogonek /en/ (before fricatives) or /om/em/ (before stops). The consonant cluster tolerance is legendary: Chrzaszcz brzmi w trzcinie (A beetle buzzes in the reeds) contains clusters English speakers find nearly impossible.\n\nCONSONANT CLUSTERS:\nPolish tolerates initial consonant clusters that seem impossible to English speakers: pszczola (bee), wstrzas (shock), drzwi (door), mgliste (misty). The key is that EVERY letter is pronounced - there are no silent letters in Polish. Practice strategies: build clusters gradually (s -> sz -> psz -> pszcz -> pszczola).\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Cannot distinguish the three sibilant series: sz/rz/cz (retroflex) vs si/zi/ci (palatal) vs s/z/c (alveolar).\n2. Cannot produce the nasal vowels (a-ogonek and e-ogonek).\n3. Overwhelmed by consonant clusters.\n4. Case ending errors - 7 cases with extensive declension.\n5. Verb aspect confusion - perfective/imperfective pairs.\n6. Gender: 3 genders PLUS masculine personal/non-personal distinction in plural.\n7. Stress always on penultimate syllable (one of the few completely regular features).\n\nCASE SYSTEM:\n7 cases: Nominative, Genitive, Dative, Accusative, Instrumental, Locative, Vocative. Three genders in singular, two gender groups in plural (masculine personal vs everything else - virile/non-virile). The masculine personal plural has distinct forms for adjectives, verbs, pronouns, and numerals.\n\nVERBAL ASPECT:\nEvery Polish verb has imperfective/perfective pair: pisac/napisac (write/have written). Aspect is fundamental - it determines which tenses are available and how actions are viewed. Polish has only 3 tenses (past, present, future) but aspect doubles the expressive range.\n\nCULTURAL CONTEXT:\nPolish hospitality, religious traditions (Polish Catholicism), food vocabulary (pierogi, bigos, zurek, barszcz). Polish history affects vocabulary: words related to partitions, WWII, Solidarity movement. Name day celebrations (imieniny). Understanding pan/pani (Mr/Mrs) as formal address.\n\nEXAM PREPARATION:\nCertyfikat Znajomosci Jezyka Polskiego: official Polish language certificate exam at B1, B2, C2 levels, administered by the State Commission for the Certification of Proficiency in Polish as a Foreign Language. Required for Polish citizenship applications.")

# Romanian
expand_file("romanian", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nRomanian preserves the Latin vowel system more closely than other Romance languages but adds two unique sounds: a-breve /a/ (a centralized mid vowel, like the a in English about) and i-circumflex/a-circumflex (both representing /i/, a close central unrounded vowel with no English equivalent - produced with the tongue in the position for i but lips unrounded and tongue slightly retracted). These two extra vowels give Romanian a distinctive sound.\n\nROMANIAN UNIQUE FEATURES AMONG ROMANCE LANGUAGES:\n1. Definite article is SUFFIXED (postposed), not prefixed: om (man) -> omul (the man), casa (house) -> casa (the house). This is unique among Romance languages and shared with Bulgarian, Albanian, and the Scandinavian languages.\n2. Case system: Romanian retains a two-case system (nominative-accusative vs genitive-dative) with distinct article forms.\n3. Three genders: masculine, feminine, and NEUTER (neuter nouns act masculine in singular and feminine in plural).\n4. Slavic vocabulary influence: approximately 10-15% of vocabulary is Slavic-origin.\n5. The subjunctive uses sa + conjugated verb: Sa mergem (Let us go).\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Not producing the a-breve and i-circumflex sounds.\n2. Placing the definite article before the noun instead of suffixing it.\n3. Confusing the neuter gender (masculine singular, feminine plural behavior).\n4. Not understanding the case system for articles and pronouns.\n5. Pronunciation of Romanian r (trilled, not English r).\n6. Word order with clitic pronouns.\n\nDIALECTAL VARIATION:\nDaco-Romanian (standard, spoken in Romania and Moldova). Moldovan is linguistically identical to Romanian but written in Cyrillic script in Transnistria. Aromanian, Megleno-Romanian, Istro-Romanian are separate Romance languages, not dialects of Romanian.\n\nCULTURAL CONTEXT:\nRomanian identity as a Latin island in a Slavic sea. Literature: Mihai Eminescu (national poet), Ion Creanga, Mircea Eliade, Emil Cioran. Cultural vocabulary: mamaliga (polenta), sarmale (stuffed cabbage), cozonac (sweet bread). Orthodox Christian traditions. Understanding of Romanian-Moldovan linguistic politics.\n\nEXAM PREPARATION:\nNo widely standardized Romanian proficiency exam for foreigners, though language requirements exist for citizenship applications and university admission.")

# Russian
expand_file("russian", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nRussian consonants come in PAIRED hard (non-palatalized) and soft (palatalized) variants - virtually every consonant has both forms. The soft sign indicates palatalization, and the letters ya, ye, yo, yu indicate soft consonant + vowel. This hard/soft distinction is phonemic and changes meaning: mat (checkmate) vs mat-soft (mother). VOWEL REDUCTION: Russian dramatically reduces unstressed vowels - unstressed o becomes /a/-like (akanye), unstressed e/a in other positions become schwa-like. The stressed vowel is the only one that keeps its full quality.\n\nCYRILLIC ALPHABET:\n33 letters including hard sign and soft sign (which are NOT vowels or consonants but modify the preceding consonant). Key letters that mislead English readers: P = r, C = s, H = n, B = v, X = kh, Y = u. Yers: hard sign separates prefix from root without palatalization, soft sign palatalizes the preceding consonant.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Not reducing unstressed vowels (especially not pronouncing unstressed o as a).\n2. Not distinguishing hard and soft consonant pairs.\n3. Case ending errors - 6 cases with complex declension patterns.\n4. Verbal aspect confusion - perfective/imperfective is fundamental.\n5. Verbs of motion: Russian has a unique paired system for going by foot vs vehicle, unidirectional vs multidirectional (idti/khodit, yekhat/yezdit), PLUS prefixed perfective forms that add directional meaning.\n6. Stress is unpredictable and shifts between forms of the same word.\n\nCASE SYSTEM:\n6 cases: Nominative, Genitive, Dative, Accusative, Instrumental, Prepositional (Locative). Three genders. Three declension classes. Adjectives decline in all cases, genders, and numbers (creating large paradigm tables).\n\nVERBS OF MOTION:\nRussian has a unique system of motion verb pairs: unidirectional vs multidirectional for each mode of transport. idti/khodit (go on foot one way/habitually), yekhat/yezdit (go by vehicle). When prefixed, these create perfective verbs with directional meanings: vyiti (go out), voiti (go in), pereiti (cross), uiti (go away), priiti (arrive). This system has approximately 14 prefix options x 2 motion types x 2 transport modes, creating a vast network of precise motion expressions.\n\nCULTURAL CONTEXT:\nRussian literature: Pushkin, Dostoevsky, Tolstoy, Chekhov, Bulgakov. The patronymic naming system (Ivan Ivanovich = Ivan son of Ivan). Russian hospitality traditions. Food: borshch, pelmeni, bliny, kasha. Russian superstitions and cultural taboos. Understanding of formal/informal register (vy/ty distinction).\n\nEXAM PREPARATION:\nTRKI/TORFL (Test of Russian as a Foreign Language): official exam system with levels A1-C2. Required for Russian university admission (B1 minimum) and certain visa categories. Administered by Russian universities worldwide.")

# Turkish
expand_file("turkish", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nTurkish has 8 vowels organized by the vowel harmony system: front unrounded e /e/, i /i/; front rounded oe /oe/, ue /y/; back unrounded a /a/, i-undotted /w/; back rounded o /o/, u /u/. The undotted i (a close back unrounded vowel) has no English equivalent - it sounds like the i in 'cousin' to English ears but is produced further back. Consonants: the distinction between c /dz/ (like English j) and c-cedilla /ch/ (like English ch) is marked only by the cedilla. K has two pronunciations: velar /k/ before back vowels, palatal /c/ before front vowels.\n\nVOWEL HARMONY:\nTurkish vowels divide into front (e, i, oe, ue) and back (a, i-undotted, o, u), and rounded (oe, ue, o, u) vs unrounded (e, i, a, i-undotted). Two-way harmony (e/a): suffixes choose front or back vowel to match the stem. Four-way harmony (i/i-undotted/ue/u): suffixes choose based on both frontness and roundedness. EVERY suffix in the language obeys vowel harmony: ev-ler-de (in houses, front) vs at-lar-da (in horses, back).\n\nAGGLUTINATIVE MORPHOLOGY:\nTurkish builds words by chaining suffixes with strict ordering. A single word can express what English needs an entire sentence for: goel-ue-n guezel-lig-i (the beauty of the lake), Avrupa-li-las-tir-il-a-ma-yan-lar-dan-mi-siniz (Are you one of those who cannot be made to become European?). Suffix categories in order: derivational -> plural -> possessive -> case -> verbal.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Not applying vowel harmony consistently across all suffixes.\n2. Cannot produce the undotted i, oe, and ue vowels.\n3. SOV word order - verb must come last.\n4. Confusing the agglutinative suffix ordering.\n5. Not understanding the definite/indefinite accusative distinction: kitap okudum (I read books/a book) vs kitabi okudum (I read THE book - accusative case marks definite objects).\n6. Relative clause structure: Turkish uses participial constructions, not wh-words.\n\nCULTURAL CONTEXT:\nTurkish hospitality vocabulary (cay, kahve, misafir). Ottoman cultural heritage. Understanding of secular/religious register differences. Food: kebab varieties, meze, baklava, ayran. Turkish bath (hamam) vocabulary. The importance of tea culture.\n\nEXAM PREPARATION:\nTomer (Turkish Teaching Centre) proficiency certificates: A1-C2. TOEMER exams administered by Ankara University. Yunus Emre Institute certification. TYS (Turkce Yeterlik Sinavi): required for university admission in Turkey.")

print("\nBatch 3 done")
