import json
import os

base = "C:/Users/user/Documents/trust-agent-desktop/src/data/roles"

def expand_file(lang, extra_content):
    fn = os.path.join(base, f"{lang}-language-tutor.json")
    with open(fn, "r", encoding="utf-8") as f:
        d = json.load(f)
    old_len = len(d["systemPrompt"])
    d["systemPrompt"] = d["systemPrompt"] + extra_content
    with open(fn, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    new_len = len(d["systemPrompt"])
    print(f"{lang}: {old_len} -> {new_len} chars")
    return new_len

# Korean
expand_file("korean", "\n\nCOMPLETE PHONOLOGICAL SYSTEM WITH IPA:\nKorean consonants exist in three series (unique among world languages): plain/lax (g, d, b, j, s), tense/fortis (kk, tt, pp, jj, ss - produced with tense throat muscles and glottalization), aspirated (k, t, p, ch, h). This three-way distinction has no equivalent in English and is the single biggest pronunciation challenge. The vowels eo and eu have no English equivalents. The distinction between eo and o and between ae and e is critical but difficult.\n\nHANGEUL SCRIPT - DEEPER:\nInvented by King Sejong the Great in 1443. A featural alphabet where consonant shapes encode articulation point. Letters grouped into syllable blocks of 2-4 characters. 14 basic consonants, 10 basic vowels, 5 double consonants, 11 combination vowels. Batchim (final consonant) rules: only 7 sounds can appear syllable-finally, causing multiple letters to neutralize. Linking rules: batchim before vowel-initial syllable moves to next syllable.\n\nSPEECH LEVELS AND HONORIFICS:\n7 historical speech levels, 4 commonly used today: Hapsyo-che (formal polite, hamnida ending), Haeyeo-che (informal polite, haeyo ending - most common), Hae-che (intimate/plain), plus archaic Hasoseo-che. Subject honorific infix -(eu)si- inserted when subject is respected. Special honorific vocabulary: meokda/deusida (eat), jada/jumusida (sleep), issda/gyesida (exist). Object honorifics for humbling own actions: juda/deurida (give).\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Cannot distinguish plain/tense/aspirated consonants - requires extensive ear training and minimal pair drills.\n2. Applying incorrect speech level - especially using intimate form with strangers or elders.\n3. SOV word order errors - the verb MUST come last in Korean.\n4. Particle confusion: wa/ga (subject), eul/reul (object), e/eseo (location) - choice depends on preceding sound.\n5. Not using honorific verb forms when speaking about or to respected persons.\n6. Irregular verb conjugation: b-irregular (deopda -> deowo), d-irregular, s-irregular, r-irregular, h-irregular patterns.\n7. Confusing eo with o - completely different vowels to Korean ears.\n\nCULTURAL CONTEXT EXPANDED:\nKorean age system and its implications for speech levels. Asking age upon meeting is normal (to determine speech level). Confucian values permeate every sentence. K-culture: K-drama, K-pop, Korean cuisine vocabulary (kimchi, bibimbap, bulgogi, tteokbokki). Hangul Day (October 9). Korean naming: family name first, typically one syllable, given name two syllables.\n\nEXAM PREPARATION:\nTOPIK (Test of Proficiency in Korean): 6 levels (1-2 beginner, 3-4 intermediate, 5-6 advanced). TOPIK I tests reading and listening. TOPIK II adds writing. Required for university admission and certain visas. EPS-TOPIK for employment permits.")

# Vietnamese
expand_file("vietnamese", "\n\nCOMPLETE TONAL SYSTEM:\nVietnamese has SIX tones in Northern standard: ngang (level, no mark) ma=ghost, sac (rising, acute) ma=cheek, huyen (falling, grave) ma=but, hoi (dipping-rising, hook) ma=tomb, nga (creaky rising, tilde) ma=horse, nang (low broken, dot below) ma=rice seedling. Southern Vietnamese merges hoi and nga into five tones. The same syllable ma has six completely different meanings depending on tone.\n\nCOMPLETE VOWEL SYSTEM:\nVietnamese has one of the richest vowel systems in the world. Monophthongs include o-horn and u-horn which have no English equivalents. Numerous diphthongs and triphthongs. The distinction between o and o-circumflex and between u and u-horn is critical.\n\nPRONOUN/KINSHIP SYSTEM:\nVietnamese has NO generic pronouns like I and you. Speakers select from kinship terms based on relative age and social relationship: toi (formal I), em (younger person), anh (older brother/you-to-older-male), chi (older sister/you-to-older-female), ong (grandfather/you-to-elderly-man), ba (grandmother). The choice establishes the entire social dynamic and changes throughout a relationship.\n\nNORTHERN VS SOUTHERN VIETNAMESE:\nNorthern (Hanoi): 6 tones, distinguishes tr/ch and s/x, considered standard for writing. Southern (Ho Chi Minh City): 5 tones (hoi and nga merge), merges several consonant pairs (tr=ch, s=x, r=g), v often becomes y. Central (Hue): distinct accent, considered difficult even for other Vietnamese speakers.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Cannot produce the six tones - particularly distinguishing hoi from nga.\n2. Cannot pronounce u-horn and o-horn vowels - no English equivalents.\n3. Ignoring final consonant unreleased stops.\n4. Using English pronouns instead of Vietnamese kinship-based system.\n5. Not understanding that Vietnamese is analytic - grammar through word order and particles, not inflection.\n6. Confusing Northern and Southern pronunciation systems.\n\nCULTURAL CONTEXT EXPANDED:\nVietnamese naming: family name first, middle name, given name - people addressed by GIVEN name (opposite of Western convention). Tet (Lunar New Year) is the most important holiday. Food vocabulary: pho, banh mi, bun, com, nuoc mam. The concept of face (the mat) governs social behavior. Indirect communication preferred over directness.")

# Punjabi
expand_file("punjabi", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nPunjabi is unique among Indo-Aryan languages in being TONAL. It has three tones: high (rising), low (falling), and level (mid). These tones developed from the loss of aspiration in voiced aspirated consonants: historical bha became ba with a low tone, gha became ga with a low tone. What was a consonant distinction in Hindi/Urdu became a tonal distinction in Punjabi.\n\nGURMUKHI vs SHAHMUKHI SCRIPTS:\nGurmukhi (Indian Punjab): 35 consonant letters, 10 vowel signs, 3 vowel carriers. Created by Sikh Guru Angad Dev ji in 16th century, left-to-right with headline. Shahmukhi (Pakistani Punjab): modified Perso-Arabic script, right-to-left. Same language, two completely different scripts depending on side of India-Pakistan border.\n\nTONAL SYSTEM - DETAILED:\nHigh tone: syllables with historical voiceless aspirated consonants in certain positions. Low tone: syllables with historical voiced aspirated consonants. Level tone: default. Minimal tonal pairs: korha (bitter, high) vs kora (lash, low) vs kora (unripe, level). Tones affect the musical quality of Punjabi and are essential for correct communication.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Ignoring tones - Punjabi tones change word meaning and must be learned.\n2. Cannot distinguish retroflex from dental consonants.\n3. Cannot produce aspirated consonants correctly.\n4. Gender agreement errors (two genders affecting adjectives and verbs).\n5. Using Hindi/Urdu vocabulary where Punjabi has its own distinct word.\n6. Confusing Gurmukhi and Shahmukhi conventions.\n\nREGIONAL DIALECTS:\nMajhi (Central Punjab, Amritsar-Lahore): considered standard. Malwai (Malwa region, Ludhiana-Patiala): largest dialect area in Indian Punjab. Doabi (between Beas and Sutlej rivers). Pothohari (northern Pakistan). Multani/Saraiki: sometimes considered a separate language.\n\nCULTURAL CONTEXT EXPANDED:\nSikh religious terminology: Waheguru (God), Gurdwara (temple), Gurbani (scripture), Ardas (prayer). Bhangra and Giddha dance/music vocabulary. Punjabi hospitality culture. Agricultural vocabulary (Punjab = land of five rivers). UK diaspora Punjabi: significant community with heritage language needs.\n\nEXAM PREPARATION:\nGCSE Punjabi (UK examination boards). Heritage language assessments. University Punjabi language courses.")

# Ukrainian
expand_file("ukrainian", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nUkrainian has 32 consonant phonemes and 6 vowel phonemes. CRITICAL: Ukrainian g letter represents a voiced glottal fricative, NOT the g in go - the hard g sound uses a special letter. Soft (palatalized) consonants: most have soft counterparts indicated by soft sign or following i/ye. Ukrainian has NO vowel reduction (unlike Russian where unstressed o sounds like a) - every vowel is pronounced clearly regardless of stress position.\n\nCYRILLIC - UKRAINIAN SPECIFICS:\n33 letters. Key differences from Russian Cyrillic: Ukrainian has i (similar to Russian sound), yi (unique), ye (unique), and apostrophe (replaces Russian hard sign). Ukrainian LACKS Russian letters for yo, hard y, ye-sound, and hard sign.\n\nUKRAINIAN VS RUSSIAN - CONTRASTIVE:\nThese are DISTINCT languages, not dialects. Ukrainian preserves Old East Slavic sounds that Russian shifted. Ukrainian has a vocative case (7 cases vs Russian 6). No vowel reduction. Different basic vocabulary: tak (yes) vs da, ale (but) vs no, de (where) vs gde. Understanding differences essential when learner knows Russian.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Pronouncing Ukrainian g as hard g instead of voiced glottal fricative - the most common error.\n2. Applying Russian vowel reduction rules to Ukrainian.\n3. Confusing Ukrainian and Russian vocabulary and grammar.\n4. Not using the vocative case (7th case Russian lacks): Ivane! Mamo! Ukraino!\n5. Stress placement errors - unpredictable, must be memorized for each word.\n6. Not distinguishing hard and soft consonants.\n\nCASE SYSTEM:\n7 cases: Nominative, Genitive, Dative, Accusative, Instrumental, Locative, Vocative. Three genders (M/F/N), two numbers. Extensive adjective and pronoun declension.\n\nVERB SYSTEM:\nAspectual pairs (perfective/imperfective) as in other Slavic languages. Past tense agrees in GENDER (not person): vin chytav (he read), vona chytala (she read), vono chytalo (it read).\n\nCULTURAL CONTEXT:\nUkrainian language deeply tied to national identity, especially since 2014 and 2022. History of language suppression and revival. Literature: Taras Shevchenko (national poet), Lesya Ukrainka, Ivan Franko. Cultural vocabulary: vyshyvanka (embroidered shirt), borshch (beetroot soup), varenyky (dumplings), pysanka (Easter egg).")

# Czech
expand_file("czech", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nCzech has the unique r-hacek sound found in NO other language in the world - a raised alveolar trill combining r and zh simultaneously. It appears in common words: tri (three), reka (river), more (sea). This is consistently the hardest sound for learners of any background. Czech also has phonemic vowel length marked by acute accent: short and long vowels change meaning (rada = council vs rada = glad).\n\nTHE UNIQUE R-HACEK:\nProduced by simultaneously trilling the tongue (like r) while adding friction (like zh). Requires months of dedicated practice. Begin by alternating r and zh rapidly, then merge them into one articulation. Practice with common words: tri, pritel, reka, dvorak.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Cannot produce r-hacek - requires months of practice.\n2. Confusing short and long vowels - they change meaning.\n3. Case ending errors - Czech has 7 cases with complex declension patterns.\n4. Stress errors - Czech stress is ALWAYS on the first syllable (with exceptions for enclitics).\n5. Not understanding verbal aspect - every verb has perfective/imperfective pair.\n6. Word order: relatively free but information structure matters.\n7. Confusing hard and soft adjective declension patterns.\n\nCASE SYSTEM - 7 CASES:\nNominative (subject), Genitive (of/from), Dative (to/for), Accusative (direct object), Vocative (direct address), Locative (about/in - always with preposition), Instrumental (by/with). Different endings for masculine animate, masculine inanimate, feminine, and neuter in singular and plural - creating massive paradigm tables. Four declension classes per gender.\n\nVERBAL ASPECT:\nEvery Czech verb exists as imperfective/perfective pair: psat/napsat (write ongoing/completed). Aspect formation: prefixation (psat->napsat), suffixation (koupit->kupovat), suppletion (brat->vzit). Only imperfective verbs have present tense meaning.\n\nCULTURAL CONTEXT:\nCzech beer culture (highest consumption per capita globally). Literature: Kafka, Kundera, Capek (who coined the word robot), Hasek (The Good Soldier Svejk). Czech humor: dry and ironic. Cuisine: knedliky (dumplings), svickova, vepro-knedlo-zelo. Diminutives are extremely common and express affection.\n\nHISTORICAL EVOLUTION:\nJan Hus reformed Czech spelling introducing the hacek system still used today (early 15th century). Czech nearly died during Habsburg rule when German was imposed, then was revived in the Czech National Revival (19th century).\n\nEXAM PREPARATION:\nCCE (Czech Language Certificate Examination) by Charles University: A1-C2 aligned with CEFR. Required for permanent residency (A1) and citizenship (B1).")

# Greek
expand_file("greek", "\n\nCOMPLETE PHONOLOGICAL SYSTEM:\nModern Greek pronunciation differs dramatically from Ancient Greek. CRITICAL: beta is NOT b but v, delta is NOT d but dh (as in this), gamma is NOT g but a voiced velar fricative (before a/o/u) or y (before e/i). To write b, d, g sounds, Greek uses digraphs: mp, nt, gk. Modern Greek has ONLY five vowel sounds but multiple spelling combinations for each: the /i/ sound can be written six different ways (iota, eta, ypsilon, ei, oi, yi). This creates significant spelling challenges.\n\nTHE GREEK ALPHABET - DETAILED:\n24 letters. Key spelling traps: six ways to write the /i/ sound, two ways to write /o/ (omicron, omega), two ways to write /e/ (epsilon, ai). Historical spelling preserved from Ancient Greek when these represented different sounds. Modern Greek uses only the acute accent (tonos) for stress marking since the 1982 monotonic reform that abolished breathing marks and other Ancient diacritics.\n\nCOMMON ERRORS BY ENGLISH SPEAKERS:\n1. Pronouncing beta as b instead of v, delta as d instead of dh, gamma as g instead of voiced velar fricative.\n2. Spelling errors with multiple representations of /i/ and /o/ sounds.\n3. Stress placement errors - Greek stress is phonemic and can fall on any of the last three syllables.\n4. Confusing three grammatical genders (masculine, feminine, neuter).\n5. Not mastering the definite article declension (12 forms for all gender/number/case combinations).\n6. Mixing Ancient and Modern Greek pronunciation.\n7. Verb conjugation errors - Greek verbs are highly inflected for person, number, tense, voice, and mood.\n\nVERB SYSTEM:\nGreek verbs conjugate for person (1st/2nd/3rd), number, tense (present, past continuous, past simple, future continuous, future simple, present perfect, past perfect, future perfect), voice (active, passive/middle), and mood (indicative, subjunctive, imperative). Two aspect stems: imperfective (continuous) and perfective (completed). Augment (e- prefix) marks past tense.\n\nMODERN vs ANCIENT GREEK:\nModern Greek lost: dative case, dual number, optative mood, infinitives (replaced by na + subjunctive), most consonant clusters, pitch accent (replaced by stress). Gained: future particle tha, subjunctive particle na, new periphrastic tenses, simplified five-vowel system.\n\nCULTURAL CONTEXT:\nGreek has a 3,400+ year written history. Modern culture: filotimo (love of honour), filoxenia (hospitality to strangers), parea (social gathering). Cuisine: moussaka, souvlaki, tzatziki, frappe. Name days (celebrated more than birthdays). Greek Orthodox traditions and calendar.\n\nEXAM PREPARATION:\nEllinomatheia: official Greek Language Certificate from Centre for the Greek Language, A1-C2 CEFR-aligned. Required for Greek citizenship and certain residency permits.")

print("\nDone with batch 1")
