import { z } from 'zod';
import { TRPCError } from '@trpc/server';
import { router, protectedProcedure } from '../trpc';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';

const s3 = new S3Client({ region: process.env.AWS_REGION || 'eu-west-2' });
const REPORTS_BUCKET = process.env.S3_REPORTS_BUCKET || 'trustagent-prod-artifacts';

// ── HTML report template ─────────────────────────────────────────────────

function generateReportHTML(data: {
  userName: string;
  roleName: string;
  companionName: string;
  category: string;
  reportType: string;
  generatedAt: string;
  sessionCount: number;
  totalMinutes: number;
  streakDays: number;
  longestStreakDays: number;
  wellbeingScore: number;
  wellbeingTrend: string;
  milestones: { type: string; achievedAt: Date }[];
  recentSessions: { startedAt: Date; durationSeconds: number | null; messageCount: number }[];
}): string {
  const totalHours = Math.floor(data.totalMinutes / 60);
  const remainingMins = data.totalMinutes % 60;

  const sessionsHTML = data.recentSessions
    .slice(0, 10)
    .map(
      (s) => `
      <tr>
        <td>${new Date(s.startedAt).toLocaleDateString('en-GB')}</td>
        <td>${Math.ceil((s.durationSeconds || 0) / 60)} mins</td>
        <td>${s.messageCount} messages</td>
      </tr>`,
    )
    .join('');

  const milestonesHTML = data.milestones
    .map(
      (m) => `<li>${m.type.replace(/_/g, ' ')} - ${new Date(m.achievedAt).toLocaleDateString('en-GB')}</li>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Progress Report - ${data.roleName}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1a1a2e; background: #fff; }
    h1 { color: #1e6fff; border-bottom: 2px solid #1e6fff; padding-bottom: 10px; }
    h2 { color: #333; margin-top: 28px; }
    .meta { color: #666; font-size: 13px; margin-bottom: 24px; }
    .stats { display: flex; gap: 20px; margin: 20px 0; }
    .stat-card { flex: 1; border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; text-align: center; }
    .stat-value { font-size: 28px; font-weight: 700; color: #1e6fff; }
    .stat-label { font-size: 12px; color: #666; text-transform: uppercase; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #eee; }
    th { font-weight: 600; color: #666; font-size: 12px; text-transform: uppercase; }
    .wellbeing { padding: 16px; border-radius: 8px; margin: 16px 0; }
    .wellbeing.stable { background: #fff8e1; border: 1px solid #ffd54f; }
    .wellbeing.improving { background: #e8f5e9; border: 1px solid #66bb6a; }
    .wellbeing.declining { background: #ffebee; border: 1px solid #ef5350; }
    .footer { margin-top: 40px; font-size: 11px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <h1>Trust Agent Progress Report</h1>
  <div class="meta">
    <strong>${data.userName}</strong> with <strong>${data.companionName}</strong> (${data.roleName})<br>
    Report type: ${data.reportType} | Generated: ${data.generatedAt}
  </div>

  <div class="stats">
    <div class="stat-card">
      <div class="stat-value">${data.sessionCount}</div>
      <div class="stat-label">Total Sessions</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">${totalHours}h ${remainingMins}m</div>
      <div class="stat-label">Total Time</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">${data.streakDays}</div>
      <div class="stat-label">Current Streak</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">${data.longestStreakDays}</div>
      <div class="stat-label">Best Streak</div>
    </div>
  </div>

  <div class="wellbeing ${data.wellbeingTrend}">
    <strong>Wellbeing Score: ${data.wellbeingScore}/100</strong> - Trend: ${data.wellbeingTrend}
  </div>

  <h2>Recent Sessions</h2>
  <table>
    <thead><tr><th>Date</th><th>Duration</th><th>Engagement</th></tr></thead>
    <tbody>${sessionsHTML || '<tr><td colspan="3">No sessions recorded</td></tr>'}</tbody>
  </table>

  ${
    data.milestones.length > 0
      ? `<h2>Milestones Achieved</h2><ul>${milestonesHTML}</ul>`
      : ''
  }

  <div class="footer">
    Generated by Trust Agent - trust-agent.ai<br>
    Session content is never included in reports. Only metadata and patterns are shown.
  </div>
</body>
</html>`;
}

export const reportsRouter = router({
  generateProgressReport: protectedProcedure
    .input(
      z.object({
        hireId: z.string(),
        reportType: z.enum(['weekly', 'monthly', 'exam_ready', 'milestone']).default('weekly'),
      }),
    )
    .mutation(async ({ input, ctx }) => {
      // Verify hire belongs to user
      const hire = await ctx.prisma.hire.findFirst({
        where: { id: input.hireId, userId: ctx.user.id },
        include: {
          role: { select: { name: true, companionName: true, category: true } },
          memory: { select: { wellbeingScore: true, wellbeingTrend: true } },
        },
      });
      if (!hire) {
        throw new TRPCError({ code: 'NOT_FOUND', message: 'Hire not found' });
      }

      // Get the date range based on report type
      const now = new Date();
      const since = new Date();
      if (input.reportType === 'weekly') since.setDate(since.getDate() - 7);
      else if (input.reportType === 'monthly') since.setDate(since.getDate() - 30);
      else since.setDate(since.getDate() - 90);

      // Fetch real session data
      const sessions = await ctx.prisma.agentSession.findMany({
        where: {
          hireId: input.hireId,
          startedAt: { gte: since },
          status: 'COMPLETED',
        },
        select: {
          startedAt: true,
          durationSeconds: true,
          messageCount: true,
        },
        orderBy: { startedAt: 'desc' },
      });

      // Fetch milestones
      const milestones = await ctx.prisma.milestone.findMany({
        where: { userId: ctx.user.id, hireId: input.hireId },
        orderBy: { achievedAt: 'desc' },
        take: 10,
      });

      const generatedAt = now.toISOString();
      const reportData = {
        userName: ctx.user.name || ctx.user.email,
        roleName: hire.role.name,
        companionName: hire.role.companionName,
        category: hire.role.category,
        reportType: input.reportType,
        generatedAt: now.toLocaleDateString('en-GB'),
        sessionCount: hire.sessionCount,
        totalMinutes: hire.totalMinutes,
        streakDays: hire.streakDays,
        longestStreakDays: hire.longestStreakDays,
        wellbeingScore: hire.memory?.wellbeingScore || 75,
        wellbeingTrend: hire.memory?.wellbeingTrend || 'stable',
        milestones: milestones.map((m) => ({ type: m.type, achievedAt: m.achievedAt })),
        recentSessions: sessions,
      };

      // Generate HTML
      const html = generateReportHTML(reportData);

      // Upload to S3
      const s3Key = `reports/${ctx.user.id}/${input.hireId}/${input.reportType}-${Date.now()}.html`;

      await s3.send(
        new PutObjectCommand({
          Bucket: REPORTS_BUCKET,
          Key: s3Key,
          Body: Buffer.from(html, 'utf-8'),
          ContentType: 'text/html',
          Metadata: {
            userId: ctx.user.id,
            hireId: input.hireId,
            reportType: input.reportType,
          },
        }),
      );

      const reportUrl = `https://${REPORTS_BUCKET}.s3.eu-west-2.amazonaws.com/${s3Key}`;

      // Save report record to DB
      const report = await ctx.prisma.progressReport.create({
        data: {
          userId: ctx.user.id,
          hireId: input.hireId,
          reportType: input.reportType,
          s3Key,
          data: reportData as object,
        },
      });

      return {
        reportId: report.id,
        reportUrl,
        s3Key,
        generatedAt,
        reportType: input.reportType,
      };
    }),

  listReports: protectedProcedure
    .input(
      z.object({
        hireId: z.string().optional(),
        limit: z.number().int().min(1).max(50).default(10),
      }),
    )
    .query(async ({ input, ctx }) => {
      const where: Record<string, unknown> = { userId: ctx.user.id };
      if (input.hireId) where.hireId = input.hireId;

      const reports = await ctx.prisma.progressReport.findMany({
        where,
        select: {
          id: true,
          hireId: true,
          reportType: true,
          s3Key: true,
          generatedAt: true,
          hire: { select: { role: { select: { name: true, companionName: true } } } },
        },
        orderBy: { generatedAt: 'desc' },
        take: input.limit,
      });

      return reports.map((r) => ({
        id: r.id,
        hireId: r.hireId,
        reportType: r.reportType,
        reportUrl: `https://${REPORTS_BUCKET}.s3.eu-west-2.amazonaws.com/${r.s3Key}`,
        generatedAt: r.generatedAt,
        roleName: r.hire.role.name,
        companionName: r.hire.role.companionName,
      }));
    }),
});
